apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability-kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 82.8.0
    helm:
      releaseName: kube-prometheus-stack
      values: |
        grafana:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.local
            path: /
            pathType: Prefix

        prometheus:
          prometheusSpec:
            retention: 7d

        alertmanager:
          enabled: true
          alertmanagerSpec:
            replicas: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true