grafana:
  enabled: true

  envFromSecret: grafana-postgres-datasource

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.dev.home.arpa
    path: /
    pathType: Prefix

  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki-gateway.observability.svc.cluster.local
      isDefault: false
      editable: false
      jsonData:
        maxLines: 1000

    - name: PostgreSQL
      uid: postgres
      type: postgres
      access: proxy
      url: postgres.dms.svc.cluster.local:5432
      user: $__env{POSTGRES_USER}
      editable: false
      secureJsonData:
        password: $__env{POSTGRES_PASSWORD}
      jsonData:
        database: $__env{POSTGRES_DB}
        sslmode: disable
        postgresVersion: 1600
        timescaledb: false