apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: dms
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi