apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
  namespace: dms
type: Opaque
stringData:
  PAPERLESS_SECRET_KEY: change-me-very-long-random-string
  PAPERLESS_ADMIN_USER: admin
  PAPERLESS_ADMIN_PASSWORD: change-me