apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-grafana-resources
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - appName: platform-observability-grafana-resources
            syncWave: "29"
  template:
    metadata:
      name: '{{ .appName }}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .syncWave }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/lars-sto/homelab.git
        targetRevision: main
        path: gitops/manifests/platform/observability/grafana/resources
      destination:
        server: https://kubernetes.default.svc
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-kube-prometheus-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: platform-observability-kube-prometheus-stack
            syncWave: "30"
  template:
    metadata:
      name: "{{appName}}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "{{syncWave}}"
    spec:
      project: default
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: kube-prometheus-stack
          targetRevision: 82.8.0
          helm:
            releaseName: kube-prometheus-stack
            valueFiles:
              - $values/gitops/manifests/platform/observability/metrics/kube-prometheus-stack/values.yaml
              - $values/gitops/manifests/platform/observability/grafana/values.yaml
        - repoURL: https://github.com/lars-sto/homelab.git
          targetRevision: main
          ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-blackbox-exporter
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - appName: platform-observability-blackbox-exporter
            syncWave: "40"
  template:
    metadata:
      name: '{{ .appName }}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .syncWave }}'
    spec:
      project: default
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: prometheus-blackbox-exporter
          targetRevision: 11.8.0
          helm:
            releaseName: blackbox-exporter
            valueFiles:
              - $values/gitops/manifests/platform/observability/metrics/blackbox-exporter/values.yaml

        - repoURL: https://github.com/lars-sto/homelab.git
          targetRevision: main
          ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-loki
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - appName: platform-observability-logs-loki
            syncWave: "45"
  template:
    metadata:
      name: '{{ .appName }}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .syncWave }}'
    spec:
      project: default
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          chart: loki
          targetRevision: 6.55.0
          helm:
            releaseName: loki
            valueFiles:
              - $values/gitops/manifests/platform/observability/logs/loki/values.yaml

        - repoURL: https://github.com/lars-sto/homelab.git
          targetRevision: main
          ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-alloy
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - appName: platform-observability-collectors-alloy
            syncWave: "50"
  template:
    metadata:
      name: '{{ .appName }}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{ .syncWave }}'
    spec:
      project: default
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          chart: alloy
          targetRevision: 1.2.0
          helm:
            releaseName: alloy
            valueFiles:
              - $values/gitops/manifests/platform/observability/collectors/alloy/values.yaml
        - repoURL: https://github.com/lars-sto/homelab.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true