grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.dev.home.arpa
    path: /
    pathType: Prefix

    additionalDataSources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki-gateway.observability.svc.cluster.local
        isDefault: false
        editable: false
        jsonData:
          maxLines: 1000

prometheus:
  prometheusSpec:
    retention: 7d

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1