apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/lars-sto/calculator-service
    newName: ghcr.io/lars-sto/calculator-service
    newTag: f59dec941ed35eb870597c2aa4500279ec35b8c6